name: 'Your Repo CI/CD Yaml Workflow'
on:
  pull_request:
    branches:
      - 'main'
jobs:
  algosec-iac-connectivity-risk-analysis:
    name: 'Algosec IAC Connectivity Risk Analysis'
    runs-on: ubuntu-latest
    steps:
      # use @actions/checkout@v3 to checkout the repo and add "USE_CHECKOUT: true" under "env:"
      - name: Checkout Repo
        uses: actions/checkout@v3
      # must use @actions/checkout@v3 before Authenticate to Google Cloud action
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.7.3
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Connectivity Risk Analysis
        uses: algosec/connectivity-risk-analysis-action@v0.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CF_TENANT_ID: ${{ secrets.CF_TENANT_ID }}
          CF_CLIENT_ID: ${{ secrets.CF_CLIENT_ID }}
          CF_CLIENT_SECRET: ${{ secrets.CF_CLIENT_SECRET }}
          # AWS Environment Variables/ External Action https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          USE_CHECKOUT: true