name: 'Your Repo CI/CD Yaml Workflow'
on:
  pull_request:
    branches:
      - 'main'
      - 'master'
jobs:
  algosec-risk-analysis:
    name: 'Algosec Risk Analysis'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: @actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.7.3
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Algosec Risk Analysis Action
        uses: algosec/connectivity-risk-analysis-action@v0.0.41
        env:
          # By default our action doesn't require actions/checkout, using GCP Auth action requires us to specify its usage
          USE_CHECKOUT: false
          ######
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CF_TENANT_ID: ${{ secrets.CF_TENANT_ID }}
          CF_CLIENT_ID: ${{ secrets.CF_CLIENT_ID }}
          CF_CLIENT_SECRET: ${{ secrets.CF_CLIENT_SECRET }}